import type { InterventionDef } from "@/types";

export const LIFESTYLE_INTERVENTIONS: InterventionDef[] = [
  {
    key: "wake",
    label: "Wake Up",
    color: "#facc15",
    icon: "🌅",
    defaultDurationMin: 60,
    params: [],
    pharmacology: {
      molecule: { name: "Wake", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        {
          target: "cortisol",
          mechanism: "agonist",
          effectGain: 8.0,
          tau: 30, // CAR duration approximation
        },
        {
          target: "dopamine",
          mechanism: "agonist",
          effectGain: 30.0,
          tau: 10,
        },
        {
          target: "melatonin",
          mechanism: "antagonist",
          effectGain: 40.0,
          tau: 20,
        },
        {
          target: "gaba",
          mechanism: "antagonist",
          effectGain: 25.0,
          tau: 45,
        },
        {
          target: "orexin",
          mechanism: "agonist",
          effectGain: 20.0,
          tau: 15,
        },
        {
          target: "acetylcholine",
          mechanism: "agonist",
          effectGain: 15.0,
          tau: 15,
        }
      ],
    },
    group: "Routine",
    categories: ["environment"],
    goals: ["energy", "focus"],
  },
  {
    key: "sleep",
    label: "Sleep",
    color: "#3b82f6",
    icon: "🌙",
    defaultDurationMin: 480,
    params: [],
    pharmacology: {
      molecule: { name: "Sleep", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        {
          target: "melatonin",
          mechanism: "agonist",
          effectGain: 80.0,
          tau: 10,
        },
        { target: "gaba", mechanism: "agonist", effectGain: 40.0, tau: 10 },
        {
          target: "histamine",
          mechanism: "antagonist",
          effectGain: 30.0,
          tau: 15,
        },
        {
          target: "orexin",
          mechanism: "antagonist",
          effectGain: 35.0,
          tau: 15,
        },
        {
          target: "adenosinePressure",
          mechanism: "antagonist",
          effectGain: 0.08,
          tau: 60,
        },
        {
          target: "growthHormone",
          mechanism: "agonist",
          effectGain: 8.0,
          tau: 2,
        },
        { target: "prolactin", mechanism: "agonist", effectGain: 5.0, tau: 30 },
        {
          target: "testosterone",
          mechanism: "agonist",
          effectGain: 3.0,
          tau: 60,
        },
        {
          target: "norepi",
          mechanism: "antagonist",
          effectGain: 25.0,
          tau: 20,
        },
        {
          target: "cortisol",
          mechanism: "antagonist",
          effectGain: 8.0,
          tau: 30,
        },
        {
          target: "serotonin",
          mechanism: "antagonist",
          effectGain: 15.0,
          tau: 30,
        },
      ],
    },
    group: "Routine",
    categories: ["environment"],
    goals: ["sleep", "recovery", "longevity", "energy"],
  },
  {
    key: "nap",
    label: "Power Nap",
    color: "#60a5fa",
    icon: "😴",
    defaultDurationMin: 25,
    params: [
      {
        key: "quality",
        label: "Refreshment",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1,
      },
    ],
    pharmacology: {
      molecule: { name: "Nap", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        { target: "gaba", mechanism: "agonist", effectGain: 25.0, tau: 5 },
        { target: "melatonin", mechanism: "agonist", effectGain: 20.0, tau: 8 },
        {
          target: "histamine",
          mechanism: "antagonist",
          effectGain: 15.0,
          tau: 10,
        },
        {
          target: "orexin",
          mechanism: "antagonist",
          effectGain: 15.0,
          tau: 10,
        },
        {
          target: "adenosinePressure",
          mechanism: "antagonist",
          effectGain: 0.04,
          tau: 20,
        },
        {
          target: "norepi",
          mechanism: "antagonist",
          effectGain: 10.0,
          tau: 10,
        },
      ],
    },
    group: "Routine",
    categories: ["wellness"],
    goals: ["sleep", "recovery", "energy", "longevity"],
  },
  {
    key: "exercise",
    label: "Exercise",
    color: "#ef4444",
    icon: "🏃",
    defaultDurationMin: 45,
    params: [
      {
        key: "type",
        label: "Type",
        type: "select",
        options: [
          { value: "cardio", label: "Cardio" },
          { value: "resistance", label: "Resistance" },
          { value: "hiit", label: "HIIT" },
        ],
        default: "cardio",
      },
    ],
    pharmacology: {
      molecule: { name: "Exercise", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        { target: "Beta_Adrenergic", mechanism: "agonist", effectGain: 1.0 },
        { target: "norepi", mechanism: "agonist", effectGain: 45.0, tau: 5 },
        {
          target: "adrenaline",
          mechanism: "agonist",
          effectGain: 200.0,
          tau: 2,
        },
        { target: "cortisol", mechanism: "agonist", effectGain: 15.0, tau: 10 },
        { target: "dopamine", mechanism: "agonist", effectGain: 20.0, tau: 5 },
        {
          target: "serotonin",
          mechanism: "agonist",
          effectGain: 12.0,
          tau: 15,
        },
        {
          target: "endocannabinoid",
          mechanism: "agonist",
          effectGain: 30.0,
          tau: 20,
        },
        {
          target: "growthHormone",
          mechanism: "agonist",
          effectGain: 6.0,
          tau: 15,
        },
        {
          target: "testosterone",
          mechanism: "agonist",
          effectGain: 4.0,
          tau: 20,
        },
        { target: "bdnf", mechanism: "agonist", effectGain: 25.0, tau: 30 },
        { target: "ampk", mechanism: "agonist", effectGain: 15.0, tau: 10 },
        { target: "glutamate", mechanism: "agonist", effectGain: 10.0, tau: 5 },
      ],
    },
    group: "Lifestyle",
    categories: ["exercise"],
    goals: ["energy", "mood", "recovery", "hormones", "longevity"],
  },
  {
    key: "alcohol",
    label: "Alcohol",
    color: "#f87171",
    icon: "🍸",
    defaultDurationMin: 60,
    params: [
      {
        key: "units",
        label: "Standard Units",
        type: "slider",
        min: 0,
        max: 10,
        step: 0.5,
        default: 1.5,
      },
    ],
    pharmacology: {
      molecule: { name: "Ethanol", molarMass: 46.07 },
      pk: {
        model: "michaelis-menten",
        bioavailability: 1.0,
        Vmax: 0.2,
        Km: 10,
        volume: { kind: "sex-adjusted", male_L_kg: 0.68, female_L_kg: 0.55 },
      },
      pd: [
        { target: "GABA_A", mechanism: "PAM", effectGain: 2.5 },
        { target: "ethanol", mechanism: "agonist", effectGain: 1.0 },
        { target: "dopamine", mechanism: "agonist", effectGain: 25.0, tau: 10 },
        { target: "NMDA", mechanism: "antagonist", Ki: 50000, effectGain: 0.2 },
        { target: "vasopressin", mechanism: "antagonist", effectGain: 10.0 },
        { target: "serotonin", mechanism: "agonist", effectGain: 10.0 },
        { target: "cortisol", mechanism: "agonist", effectGain: 10.0 },
        { target: "inflammation", mechanism: "agonist", effectGain: 0.5 },
        { target: "testosterone", mechanism: "antagonist", effectGain: 5.0 },
      ],
    },
    group: "Lifestyle",
    categories: ["social"],
    goals: ["mood", "calm"],
  },
  {
    key: "social",
    label: "Social Interaction",
    color: "#f472b6",
    icon: "🗣️",
    defaultDurationMin: 60,
    params: [],
    pharmacology: {
      molecule: { name: "Social", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        { target: "oxytocin", mechanism: "agonist", effectGain: 5.0, tau: 10 },
        { target: "dopamine", mechanism: "agonist", effectGain: 20.0, tau: 15 },
        {
          target: "serotonin",
          mechanism: "agonist",
          effectGain: 10.0,
          tau: 15,
        },
        { target: "cortisol", mechanism: "antagonist", effectGain: 10.0 },
        { target: "vagal", mechanism: "agonist", effectGain: 0.4 },
        { target: "endocannabinoid", mechanism: "agonist", effectGain: 15.0 },
      ],
    },
    group: "Lifestyle",
    categories: ["social"],
    goals: ["mood", "hormones"],
  },
  {
    key: "meditation",
    label: "Meditation",
    color: "#60a5fa",
    icon: "🧘",
    defaultDurationMin: 20,
    params: [],
    pharmacology: {
      molecule: { name: "Meditation", molarMass: 0 },
      pk: { model: "activity-dependent" },
      pd: [
        { target: "vagal", mechanism: "agonist", effectGain: 0.6, tau: 5 },
        { target: "gaba", mechanism: "agonist", effectGain: 15.0, tau: 8 },
        { target: "cortisol", mechanism: "antagonist", effectGain: 5.0 },
        { target: "serotonin", mechanism: "agonist", effectGain: 12.0 },
        { target: "norepi", mechanism: "antagonist", effectGain: 15.0 },
        { target: "inflammation", mechanism: "antagonist", effectGain: 0.2 },
        { target: "melatonin", mechanism: "agonist", effectGain: 5.0 },
      ],
    },
    group: "Wellness",
    categories: ["wellness"],
    goals: ["calm", "focus", "mood", "longevity"],
  },
];
